(* generated by domino: invariant for Hybrid1 ~ Hybrid2 *)

require import AllCore Distr FMap Int IntDiv Types.

type KX_NoKeys_pkgstate = {
  KX_NoKeys_d_LTK : (int, bits_n) fmap;
  KX_NoKeys_d_H : (int, bool) fmap;
  KX_NoKeys_ctr_ : int;
  KX_NoKeys_kid_ : int;
  KX_NoKeys_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_NoKeys_d_Fresh : (int, bool) fmap;
  KX_NoKeys_d_State : (int, (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type PRF_pkgstate = {
  PRF_d_LTK : (int, bits_n) fmap;
  PRF_d_H : (int, bool) fmap;
  PRF_d_PRF : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap;
  PRF_kid_ : int
}.

type KX_NoPrf_pkgstate = {
  KX_NoPrf_ctr_ : int;
  KX_NoPrf_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_NoPrf_d_Fresh : (int, bool) fmap;
  KX_NoPrf_d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type Hybrid1_state = {
  l_pkg_KX : KX_NoKeys_pkgstate;
  l_pkg_KX_b : bool;
  l_abort_flag : bool
}.

type Hybrid2_state = {
  r_pkg_Prf : PRF_pkgstate;
  r_pkg_KX : KX_NoPrf_pkgstate;
  r_pkg_Prf_b : bool;
  r_pkg_KX_b : bool;
  r_abort_flag : bool
}.

op StateRelation_state_eq (l : Hybrid1_state) (r : Hybrid2_state) : bool =
  forall (ctr : int),
       (l.`l_pkg_KX.`KX_NoKeys_d_State.[ctr] = None) = (r.`r_pkg_KX.`KX_NoPrf_d_State.[ctr] = None)
    /\ (let state = r.`r_pkg_KX.`KX_NoPrf_d_State.[ctr] in
             !(state = None)
          => let d_U = (oget state).`1 in
               let u = (oget state).`2 in
                 let d_V = (oget state).`3 in
                   let kid = (oget state).`4 in
                     let acc = (oget state).`5 in
                       let ni = (oget state).`6 in
                         let nr = (oget state).`7 in
                           let kmac = (oget state).`8 in
                             let sid = (oget state).`9 in
                               let mess = (oget state).`10 in
                                 let ltk = r.`r_pkg_Prf.`PRF_d_LTK.[kid] in
                                      !(ltk = None)
                                   /\ l.`l_pkg_KX.`KX_NoKeys_d_State.[ctr] = Some (d_U, u, d_V, oget ltk, acc, ni, nr, kmac, sid, mess)).

op StateRelation_invariant (l : Hybrid1_state) (r : Hybrid2_state) : bool =
     l.`l_pkg_KX.`KX_NoKeys_kid_ = r.`r_pkg_Prf.`PRF_kid_
  /\ l.`l_pkg_KX.`KX_NoKeys_ctr_ = r.`r_pkg_KX.`KX_NoPrf_ctr_
  /\ l.`l_pkg_KX.`KX_NoKeys_d_LTK = r.`r_pkg_Prf.`PRF_d_LTK
  /\ l.`l_pkg_KX.`KX_NoKeys_d_H = r.`r_pkg_Prf.`PRF_d_H
  /\ l.`l_pkg_KX.`KX_NoKeys_d_Fresh = r.`r_pkg_KX.`KX_NoPrf_d_Fresh
  /\ l.`l_pkg_KX.`KX_NoKeys_d_RevTested = r.`r_pkg_KX.`KX_NoPrf_d_RevTested
  /\ StateRelation_state_eq l r.

(* skipped `define-fun randomness-mapping-NewKey` (randomness mapping, not translated) *)

op PkgInv_PRF (s : PRF_pkgstate) : bool =
     (forall (kid : int),
           (s.`PRF_kid_ < kid \/ kid <= 0) = (s.`PRF_d_H.[kid] = None)
        /\ (s.`PRF_d_H.[kid] = None) = (s.`PRF_d_LTK.[kid] = None))
  /\ 0 <= s.`PRF_kid_.

op PkgInv_r_Prf (r : Hybrid2_state) : bool =
  PkgInv_PRF r.`r_pkg_Prf.

op GameInv_Hybrid2 (g : Hybrid2_state) : bool =
  forall (ctr : int),
    let state = g.`r_pkg_KX.`KX_NoPrf_d_State.[ctr] in
         !(state = None)
      => let kid = (oget state).`4 in
              !(g.`r_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = None)
           /\ !(g.`r_pkg_Prf.`PRF_d_H.[kid] = None)
           /\ g.`r_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = g.`r_pkg_Prf.`PRF_d_H.[kid].

op params_inv (l : Hybrid1_state) (r : Hybrid2_state) : bool =
     r.`r_pkg_Prf_b = false
  /\ l.`l_pkg_KX_b = r.`r_pkg_KX_b.

op inv (l : Hybrid1_state) (r : Hybrid2_state) : bool =
     params_inv l r
  /\ l.`l_abort_flag = r.`r_abort_flag
  /\ (   !l.`l_abort_flag
      =>    StateRelation_invariant l r
         /\ PkgInv_r_Prf r
         /\ GameInv_Hybrid2 r).
