(* generated by domino: invariant for Real_Hybrid3 ~ Ideal_Hybrid3 *)

require import AllCore Distr FMap Int IntDiv Types.

type PRF_pkgstate = {
  PRF_d_LTK : (int, bits_n) fmap;
  PRF_d_H : (int, bool) fmap;
  PRF_d_PRF : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap;
  PRF_kid_ : int
}.

type KX_NoPrf_pkgstate = {
  KX_NoPrf_ctr_ : int;
  KX_NoPrf_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_NoPrf_d_Fresh : (int, bool) fmap;
  KX_NoPrf_d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type Real_Hybrid3_state = {
  l_pkg_Prf : PRF_pkgstate;
  l_pkg_KX : KX_NoPrf_pkgstate;
  l_pkg_Prf_b : bool;
  l_pkg_KX_b : bool;
  l_abort_flag : bool
}.

type Ideal_Hybrid3_state = {
  r_pkg_Prf : PRF_pkgstate;
  r_pkg_KX : KX_NoPrf_pkgstate;
  r_pkg_Prf_b : bool;
  r_pkg_KX_b : bool;
  r_abort_flag : bool
}.

op Helper_eq_prf (left_prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) (right_prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) (hon : (int, bool) fmap) : bool =
  forall (kid : int) (d_U : int) (d_V : int) (ni : bits_n) (nr : bits_n),
    let kmac_index = (kid, (d_U, d_V, ni, nr, false)) in
      let k_index = (kid, (d_U, d_V, ni, nr, true)) in
           (   !(right_prf.[k_index] = None)
            => left_prf.[k_index] = right_prf.[k_index])
        /\ left_prf.[kmac_index] = right_prf.[kmac_index].

op Helper_no_overwriting_state (max_ctr : int) (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    (max_ctr < ctr \/ ctr <= 0) = (d_State.[ctr] = None).

op Helper_kmac_before_sid (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let kmac = (oget state).`8 in
           let sid = (oget state).`9 in
                kmac = None
             => sid = None.

op Helper_referenced_kid_exist (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) (d_Ltk : (int, bits_n) fmap) : bool =
     (forall (kid : int) (d_U : int) (d_V : int) (ni : bits_n) (nr : bits_n) (flag : bool),
           d_Ltk.[kid] = None
        => d_Prf.[(kid, (d_U, d_V, ni, nr, flag))] = None)
  /\ (forall (ctr : int),
        let state = d_State.[ctr] in
             !(state = None)
          => let kid = (oget state).`4 in
               !(d_Ltk.[kid] = None)).

op Helper_k_prf_implies_rev_tested_sid (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) (d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap) : bool =
  forall (kid : int) (d_U : int) (d_V : int) (ni : bits_n) (nr : bits_n),
       !(d_Prf.[(kid, (d_U, d_V, ni, nr, true))] = None)
    => let kmac = oget d_Prf.[(kid, (d_U, d_V, ni, nr, false))] in
         let tau = func_mac kmac nr 2 in
           !(d_RevTested.[(d_U, d_V, ni, nr, tau)] = None).

op Helper_sid_is_wellformed (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) (d_H : (int, bool) fmap) (d_Ltk : (int, bits_n) fmap) (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let d_U = (oget state).`1 in
           let u = (oget state).`2 in
             let d_V = (oget state).`3 in
               let kid = (oget state).`4 in
                 let acc = (oget state).`5 in
                   let ni = (oget state).`6 in
                     let nr = (oget state).`7 in
                       let kmac = (oget state).`8 in
                         let sid = (oget state).`9 in
                           let mess = (oget state).`10 in
                                !(sid = None)
                             => sid = Some (d_U, d_V, oget ni, oget nr, func_mac (oget kmac) (oget nr) 2).

op Helper_kmac_requires_nonces (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let ni = (oget state).`6 in
           let nr = (oget state).`7 in
             let kmac = (oget state).`8 in
                  !(kmac = None)
               =>    !(ni = None)
                  /\ !(nr = None).

op Helper_sid_requires_nonces (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let ni = (oget state).`6 in
           let nr = (oget state).`7 in
             let sid = (oget state).`9 in
                  !(sid = None)
               =>    !(ni = None)
                  /\ !(nr = None).

op Helper_no_sid_in_send1 (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let sid = (oget state).`9 in
           let mess = (oget state).`10 in
                mess = 0
             => sid = None.

op Helper_no_kmac_in_send1 (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let kmac = (oget state).`8 in
           let mess = (oget state).`10 in
                mess = 0
             => kmac = None.

op Helper_kmac_is_wellformed (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) (d_Fresh : (int, bool) fmap) (d_Ltk : (int, bits_n) fmap) (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let d_U = (oget state).`1 in
           let u = (oget state).`2 in
             let d_V = (oget state).`3 in
               let kid = (oget state).`4 in
                 let acc = (oget state).`5 in
                   let ni = (oget state).`6 in
                     let nr = (oget state).`7 in
                       let kmac = (oget state).`8 in
                         let sid = (oget state).`9 in
                           let mess = (oget state).`10 in
                                !(kmac = None)
                             => oget kmac = (if d_Fresh.[ctr] = Some true then oget d_Prf.[(kid, (d_U, d_V, oget ni, oget nr, false))] else func_prf (oget d_Ltk.[kid]) (d_U, d_V, oget ni, oget nr, false)).

op Helper_honest_kmac (d_State : (int, (int * bool * int * int * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap) (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) (d_Fresh : (int, bool) fmap) (d_H : (int, bool) fmap) : bool =
  forall (ctr : int),
    let state = d_State.[ctr] in
         !(state = None)
      => let d_U = (oget state).`1 in
           let u = (oget state).`2 in
             let d_V = (oget state).`3 in
               let kid = (oget state).`4 in
                 let acc = (oget state).`5 in
                   let ni = (oget state).`6 in
                     let nr = (oget state).`7 in
                       let kmac = (oget state).`8 in
                         let sid = (oget state).`9 in
                           let mess = (oget state).`10 in
                                d_Fresh.[ctr] = Some true
                             =>    d_H.[kid] = Some true
                                /\ (   !(kmac = None)
                                    => !(d_Prf.[(kid, (d_U, d_V, oget ni, oget nr, false))] = None)).

op Helper_kmac_before_k (d_Prf : ((int * (int * int * bits_n * bits_n * bool)), bits_n) fmap) : bool =
  forall (kid : int) (d_U : int) (d_V : int) (ni : bits_n) (nr : bits_n),
       d_Prf.[(kid, (d_U, d_V, ni, nr, false))] = None
    => d_Prf.[(kid, (d_U, d_V, ni, nr, true))] = None.

op StateRelation_invariant (l : Real_Hybrid3_state) (r : Ideal_Hybrid3_state) : bool =
     0 <= l.`l_pkg_KX.`KX_NoPrf_ctr_
  /\ l.`l_pkg_Prf.`PRF_kid_ = r.`r_pkg_Prf.`PRF_kid_
  /\ l.`l_pkg_KX.`KX_NoPrf_ctr_ = r.`r_pkg_KX.`KX_NoPrf_ctr_
  /\ l.`l_pkg_Prf.`PRF_d_LTK = r.`r_pkg_Prf.`PRF_d_LTK
  /\ Helper_eq_prf l.`l_pkg_Prf.`PRF_d_PRF r.`r_pkg_Prf.`PRF_d_PRF l.`l_pkg_Prf.`PRF_d_H
  /\ l.`l_pkg_Prf.`PRF_d_H = r.`r_pkg_Prf.`PRF_d_H
  /\ l.`l_pkg_KX.`KX_NoPrf_d_Fresh = r.`r_pkg_KX.`KX_NoPrf_d_Fresh
  /\ l.`l_pkg_KX.`KX_NoPrf_d_RevTested = r.`r_pkg_KX.`KX_NoPrf_d_RevTested
  /\ l.`l_pkg_KX.`KX_NoPrf_d_State = r.`r_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_no_overwriting_state l.`l_pkg_KX.`KX_NoPrf_ctr_ l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_kmac_requires_nonces l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_kmac_is_wellformed l.`l_pkg_KX.`KX_NoPrf_d_State l.`l_pkg_KX.`KX_NoPrf_d_Fresh l.`l_pkg_Prf.`PRF_d_LTK l.`l_pkg_Prf.`PRF_d_PRF
  /\ Helper_no_kmac_in_send1 l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_sid_requires_nonces l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_sid_is_wellformed l.`l_pkg_KX.`KX_NoPrf_d_State l.`l_pkg_Prf.`PRF_d_H l.`l_pkg_Prf.`PRF_d_LTK l.`l_pkg_Prf.`PRF_d_PRF
  /\ Helper_no_sid_in_send1 l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_kmac_before_sid l.`l_pkg_KX.`KX_NoPrf_d_State
  /\ Helper_kmac_before_k l.`l_pkg_Prf.`PRF_d_PRF
  /\ Helper_kmac_before_k r.`r_pkg_Prf.`PRF_d_PRF
  /\ Helper_referenced_kid_exist l.`l_pkg_KX.`KX_NoPrf_d_State l.`l_pkg_Prf.`PRF_d_PRF l.`l_pkg_Prf.`PRF_d_LTK
  /\ Helper_k_prf_implies_rev_tested_sid l.`l_pkg_Prf.`PRF_d_PRF l.`l_pkg_KX.`KX_NoPrf_d_RevTested
  /\ Helper_honest_kmac l.`l_pkg_KX.`KX_NoPrf_d_State l.`l_pkg_Prf.`PRF_d_PRF l.`l_pkg_KX.`KX_NoPrf_d_Fresh l.`l_pkg_Prf.`PRF_d_H.

(* skipped `define-fun randomness-mapping-Test` (randomness mapping, not translated) *)

op PkgInv_PRF (s : PRF_pkgstate) : bool =
     (forall (kid : int),
           (s.`PRF_kid_ < kid \/ kid <= 0) = (s.`PRF_d_H.[kid] = None)
        /\ (s.`PRF_d_H.[kid] = None) = (s.`PRF_d_LTK.[kid] = None))
  /\ 0 <= s.`PRF_kid_.

op PkgInv_l_Prf (l : Real_Hybrid3_state) : bool =
  PkgInv_PRF l.`l_pkg_Prf.

op PkgInv_r_Prf (r : Ideal_Hybrid3_state) : bool =
  PkgInv_PRF r.`r_pkg_Prf.

op GameInv_Real_Hybrid3 (g : Real_Hybrid3_state) : bool =
  forall (ctr : int),
    let state = g.`l_pkg_KX.`KX_NoPrf_d_State.[ctr] in
         !(state = None)
      => let kid = (oget state).`4 in
              !(g.`l_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = None)
           /\ !(g.`l_pkg_Prf.`PRF_d_H.[kid] = None)
           /\ g.`l_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = g.`l_pkg_Prf.`PRF_d_H.[kid].

op GameInv_Ideal_Hybrid3 (g : Ideal_Hybrid3_state) : bool =
  forall (ctr : int),
    let state = g.`r_pkg_KX.`KX_NoPrf_d_State.[ctr] in
         !(state = None)
      => let kid = (oget state).`4 in
              !(g.`r_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = None)
           /\ !(g.`r_pkg_Prf.`PRF_d_H.[kid] = None)
           /\ g.`r_pkg_KX.`KX_NoPrf_d_Fresh.[ctr] = g.`r_pkg_Prf.`PRF_d_H.[kid].

op params_inv (l : Real_Hybrid3_state) (r : Ideal_Hybrid3_state) : bool =
     l.`l_pkg_Prf_b = true
  /\ l.`l_pkg_KX_b = false
  /\ r.`r_pkg_Prf_b = true
  /\ r.`r_pkg_KX_b = true.

op inv (l : Real_Hybrid3_state) (r : Ideal_Hybrid3_state) : bool =
     params_inv l r
  /\ l.`l_abort_flag = r.`r_abort_flag
  /\ (   !l.`l_abort_flag
      =>    StateRelation_invariant l r
         /\ PkgInv_l_Prf l
         /\ GameInv_Real_Hybrid3 l
         /\ PkgInv_r_Prf r
         /\ GameInv_Ideal_Hybrid3 r).
