(* generated by domino: invariant for Hybrid0 ~ Hybrid1 *)

require import AllCore Distr FMap Int IntDiv Types.

type KX_pkgstate = {
  KX_d_LTK : (int, bits_n) fmap;
  KX_d_H : (int, bool) fmap;
  KX_ctr_ : int;
  KX_kid_ : int;
  KX_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_d_Fresh : (int, bool) fmap;
  KX_d_First : ((int * int * bits_n * bits_n * bits_n), int) fmap;
  KX_d_Second : ((int * int * bits_n * bits_n * bits_n), int) fmap;
  KX_d_State : (int, (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type KX_NoKeys_pkgstate = {
  KX_NoKeys_d_LTK : (int, bits_n) fmap;
  KX_NoKeys_d_H : (int, bool) fmap;
  KX_NoKeys_ctr_ : int;
  KX_NoKeys_kid_ : int;
  KX_NoKeys_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_NoKeys_d_Fresh : (int, bool) fmap;
  KX_NoKeys_d_State : (int, (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type Hybrid0_state = {
  l_pkg_KX : KX_pkgstate;
  l_pkg_KX_b : bool;
  l_abort_flag : bool
}.

type Hybrid1_state = {
  r_pkg_KX : KX_NoKeys_pkgstate;
  r_pkg_KX_b : bool;
  r_abort_flag : bool
}.

op Domino_state_eq (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  forall (ctr : int),
       (l.`l_pkg_KX.`KX_d_State.[ctr] = None) = (r.`r_pkg_KX.`KX_NoKeys_d_State.[ctr] = None)
    /\ (let state = l.`l_pkg_KX.`KX_d_State.[ctr] in
             !(state = None)
          => let d_U = (oget state).`1 in
               let u = (oget state).`2 in
                 let d_V = (oget state).`3 in
                   let ltk = (oget state).`4 in
                     let acc = (oget state).`5 in
                       let k = (oget state).`6 in
                         let ni = (oget state).`7 in
                           let nr = (oget state).`8 in
                             let kmac = (oget state).`9 in
                               let sid = (oget state).`10 in
                                 let mess = (oget state).`11 in
                                   r.`r_pkg_KX.`KX_NoKeys_d_State.[ctr] = Some (d_U, u, d_V, ltk, acc, ni, nr, kmac, sid, mess)).

op Domino_keys_computed_correctly (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  forall (ctr : int),
    let state = l.`l_pkg_KX.`KX_d_State.[ctr] in
         !(state = None)
      => let d_U = (oget state).`1 in
           let u = (oget state).`2 in
             let d_V = (oget state).`3 in
               let ltk = (oget state).`4 in
                 let acc = (oget state).`5 in
                   let k = (oget state).`6 in
                     let ni = (oget state).`7 in
                       let nr = (oget state).`8 in
                         let kmac = (oget state).`9 in
                           let sid = (oget state).`10 in
                             let mess = (oget state).`11 in
                               if u /\ 0 < mess \/ !u /\ 1 < mess then k = Some (func_prf ltk (d_U, d_V, oget ni, oget nr, true)) else k = None.

op Domino_time_of_acceptance (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  forall (ctr : int),
    let state = l.`l_pkg_KX.`KX_d_State.[ctr] in
         !(state = None)
      => let u = (oget state).`2 in
           let acc = (oget state).`5 in
             let mess = (oget state).`11 in
                  !(acc = None)
               => if u then 1 < mess else 2 < mess.

op Domino_time_of_nonces (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  forall (ctr : int),
    let state = l.`l_pkg_KX.`KX_d_State.[ctr] in
         !(state = None)
      => let u = (oget state).`2 in
           let ni = (oget state).`7 in
             let nr = (oget state).`8 in
               let mess = (oget state).`11 in
                    (   0 < mess
                     => !(ni = None))
                 /\ (         0 < mess
                           /\ u
                        \/    1 < mess
                           /\ !u
                     => !(nr = None)).

op Domino_time_of_sid (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  forall (ctr : int),
    let state = l.`l_pkg_KX.`KX_d_State.[ctr] in
         !(state = None)
      => let u = (oget state).`2 in
           let sid = (oget state).`10 in
             let mess = (oget state).`11 in
                        0 < mess
                     /\ u
                  \/    1 < mess
                     /\ !u
               => !(sid = None).

op Domino_invariant (l : Hybrid0_state) (r : Hybrid1_state) : bool =
     l.`l_pkg_KX.`KX_kid_ = r.`r_pkg_KX.`KX_NoKeys_kid_
  /\ l.`l_pkg_KX.`KX_ctr_ = r.`r_pkg_KX.`KX_NoKeys_ctr_
  /\ l.`l_pkg_KX.`KX_d_LTK = r.`r_pkg_KX.`KX_NoKeys_d_LTK
  /\ l.`l_pkg_KX.`KX_d_H = r.`r_pkg_KX.`KX_NoKeys_d_H
  /\ l.`l_pkg_KX.`KX_d_Fresh = r.`r_pkg_KX.`KX_NoKeys_d_Fresh
  /\ l.`l_pkg_KX.`KX_d_RevTested = r.`r_pkg_KX.`KX_NoKeys_d_RevTested
  /\ Domino_state_eq l r
  /\ Domino_keys_computed_correctly l r
  /\ Domino_time_of_nonces l r
  /\ Domino_time_of_sid l r
  /\ Domino_time_of_acceptance l r.

op params_inv (l : Hybrid0_state) (r : Hybrid1_state) : bool =
  l.`l_pkg_KX_b = r.`r_pkg_KX_b.

op inv (l : Hybrid0_state) (r : Hybrid1_state) : bool =
     params_inv l r
  /\ l.`l_abort_flag = r.`r_abort_flag
  /\ (   !l.`l_abort_flag
      => Domino_invariant l r).
