(* generated by domino: invariant for H1_1 ~ H2_0 *)

require import AllCore Distr FMap Int IntDiv Types.

type Nonces_pkgstate = {
  Nonces_d_Nonces : (bits_n, bool) fmap
}.

type KX_pkgstate = {
  KX_d_LTK : (int, bits_n) fmap;
  KX_d_H : (int, bool) fmap;
  KX_ctr_ : int;
  KX_kid_ : int;
  KX_d_RevTested : ((int * int * bits_n * bits_n * bits_n), bool) fmap;
  KX_d_Fresh : (int, bool) fmap;
  KX_d_First : ((int * int * bits_n * bits_n * bits_n), int) fmap;
  KX_d_Second : ((int * int * bits_n * bits_n * bits_n), int) fmap;
  KX_d_State : (int, (int * bool * int * bits_n * bool option * bits_n option * bits_n option * bits_n option * bits_n option * (int * int * bits_n * bits_n * bits_n) option * int)) fmap
}.

type CR_pkgstate = {
  CR_d_PRFinverse : (bits_n, (bits_n * (int * int * bits_n * bits_n * bool))) fmap;
  CR_d_MACinverse : (bits_n, (bits_n * bits_n * int)) fmap
}.

type H1_1_state = {
  l_pkg_Nonces : Nonces_pkgstate;
  l_pkg_KX : KX_pkgstate;
  l_pkg_Nonces_b : bool;
  l_pkg_KX_b : bool;
  l_abort_flag : bool
}.

type H2_0_state = {
  r_pkg_Nonces : Nonces_pkgstate;
  r_pkg_CR : CR_pkgstate;
  r_pkg_KX : KX_pkgstate;
  r_pkg_Nonces_b : bool;
  r_pkg_CR_b : bool;
  r_pkg_KX_b : bool;
  r_abort_flag : bool
}.

op StateRelation_invariant (l : H1_1_state) (r : H2_0_state) : bool =
     l.`l_pkg_KX = r.`r_pkg_KX
  /\ l.`l_pkg_Nonces = r.`r_pkg_Nonces.

op params_inv (l : H1_1_state) (r : H2_0_state) : bool =
     l.`l_pkg_Nonces_b = true
  /\ r.`r_pkg_Nonces_b = true
  /\ r.`r_pkg_CR_b = false
  /\ l.`l_pkg_KX_b = r.`r_pkg_KX_b.

op inv (l : H1_1_state) (r : H2_0_state) : bool =
     params_inv l r
  /\ l.`l_abort_flag = r.`r_abort_flag
  /\ (   !l.`l_abort_flag
      => StateRelation_invariant l r).
